apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ecommerce
spec:
  project: ecommerce
  source:
    repoURL: https://github.com/mohammedfirdouss/k8s.git
    targetRevision: HEAD
    path: k8s/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
