apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ecommerce
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: ecommerce
  source:
    repoURL: https://github.com/mohammedfirdouss/k8s.git
    targetRevision: HEAD
    path: k8s/base/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
